name: Deploy to Nexus Repository

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: npm install

            - name: Build the app
              run: npm run build

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: app
                  path: build

            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: app

            - name: Deploy to Nexus Repository
              run: |
                  curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} --upload-file ./app/* YOUR_NEXUS_URL

            # Add any other necessary steps here for post-deployment actions or verifications
