name: OWASP ZAP Baseline Scan

on:
    push:
        branches:
            - main
jobs:
    dast:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: OWASP ZAP Baseline Scan
            # You may pin to the exact commit or the version.
            # uses: zaproxy/action-baseline@1a33faea4d2caa248054dc306a56525eedd3bbea
              uses: zaproxy/action-baseline@v0.8.2
              with:
                # GitHub Token to create issues in the repository
              
                # Target URL
                target: https://github.com/snrakshith/csh-fe-template/
                # Relative path of the ZAP configuration file
               
